/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaddleOption.java
 *
 * Created on May 3, 2010, 2:03:41 PM
 */
package pongproject;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 * The frame that contains the options for the paddles
 * @author Mark & Sam
 */
public class PaddleOption extends javax.swing.JFrame implements KeyListener
{

    /** The canvas for the program*/
    PongCanvas canvas;
    /** Array of booleans to determine which direction option gets the input*/
    boolean[] buttonFocus = new boolean[ 4 ];

    /**
     * Creates new form PaddleOption
     * @param canvas - the canvas for the program
     */
    public PaddleOption( PongCanvas canvas )
    {
        this.canvas = canvas;
        initComponents();
        Pad1Color.setBackground( canvas.getPad1Color() );
        Pad2Color.setBackground( canvas.getPad2Color() );
        this.setLocation( canvas.getX(), canvas.getY() );
        P1Up.setText( "" + ( char ) canvas.getP1Up() );
        P1Down.setText( "" + ( char ) canvas.getP1Down() );
        P2Up.setText( "" + ( char ) canvas.getP2Up() );
        P2Down.setText( "" + ( char ) canvas.getP2Down() );
        buttonFocus[0] = false;
        buttonFocus[1] = false;
        buttonFocus[2] = false;
        buttonFocus[3] = false;
        this.addKeyListener( this );
        jButton1.addKeyListener( this );
        jButton2.addKeyListener( this );
        jButton3.addKeyListener( this );
        jButton4.addKeyListener( this );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSizeTwo = new javax.swing.JTextField();
        jTextFieldSizeOne = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSpeedTwo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSpeedOne = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ButtonCol1 = new javax.swing.JButton();
        Pad1Color = new javax.swing.JPanel();
        Pad2Color = new javax.swing.JPanel();
        ButtonCol2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        P2Up = new javax.swing.JLabel();
        P2Down = new javax.swing.JLabel();
        P1Up = new javax.swing.JLabel();
        P1Down = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pongproject.PongProjectApp.class).getContext().getResourceMap(PaddleOption.class);
        jButtonOK.setText(resourceMap.getString("jButtonOK.text")); // NOI18N
        jButtonOK.setName("jButtonOK"); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextFieldSizeTwo.setName("jTextFieldSizeTwo"); // NOI18N

        jTextFieldSizeOne.setName("jTextFieldSizeOne"); // NOI18N

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldSpeedTwo.setName("jTextFieldSpeedTwo"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextFieldSpeedOne.setName("jTextFieldSpeedOne"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        ButtonCol1.setText(resourceMap.getString("ButtonCol1.text")); // NOI18N
        ButtonCol1.setName("ButtonCol1"); // NOI18N
        ButtonCol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCol1ActionPerformed(evt);
            }
        });

        Pad1Color.setName("Pad1Color"); // NOI18N

        javax.swing.GroupLayout Pad1ColorLayout = new javax.swing.GroupLayout(Pad1Color);
        Pad1Color.setLayout(Pad1ColorLayout);
        Pad1ColorLayout.setHorizontalGroup(
            Pad1ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        Pad1ColorLayout.setVerticalGroup(
            Pad1ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        Pad2Color.setName("Pad2Color"); // NOI18N

        javax.swing.GroupLayout Pad2ColorLayout = new javax.swing.GroupLayout(Pad2Color);
        Pad2Color.setLayout(Pad2ColorLayout);
        Pad2ColorLayout.setHorizontalGroup(
            Pad2ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        Pad2ColorLayout.setVerticalGroup(
            Pad2ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        ButtonCol2.setText(resourceMap.getString("ButtonCol2.text")); // NOI18N
        ButtonCol2.setName("ButtonCol2"); // NOI18N
        ButtonCol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCol2ActionPerformed(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        P2Up.setText(resourceMap.getString("P2Up.text")); // NOI18N
        P2Up.setName("P2Up"); // NOI18N

        P2Down.setText(resourceMap.getString("P2Down.text")); // NOI18N
        P2Down.setName("P2Down"); // NOI18N

        P1Up.setText(resourceMap.getString("P1Up.text")); // NOI18N
        P1Up.setName("P1Up"); // NOI18N

        P1Down.setText(resourceMap.getString("P1Down.text")); // NOI18N
        P1Down.setName("P1Down"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSpeedOne)
                                    .addComponent(jTextFieldSizeTwo)
                                    .addComponent(jTextFieldSizeOne, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSpeedTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pad1Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCol1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(P1Down)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(P1Up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pad2Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCol2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(P2Down)
                            .addComponent(P2Up))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSizeOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSizeTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSpeedOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldSpeedTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ButtonCol1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pad1Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ButtonCol2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pad2Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(P2Up))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(P2Down))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P1Up)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(P1Down))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Finalizes the options
     * @param evt - the event
     */
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        int sizeOne;
        int sizeTwo;
        int speedOne;
        int speedTwo;

        try
        {
            sizeOne = Integer.parseInt( jTextFieldSizeOne.getText() );
            if( sizeOne > 80 )
                sizeOne = 80;
            canvas.setPad1Size( sizeOne );
        }
        catch( Exception e )
        {
            if( jTextFieldSizeOne.getText() != null )
                System.out.println( "Pad One size invalid." );
        }

        try
        {
            sizeTwo = Integer.parseInt( jTextFieldSizeTwo.getText() );
            if( sizeTwo > 80 )
                sizeTwo = 80;

            canvas.setPad2Size( sizeTwo );
        }
        catch( Exception e )
        {
            if( jTextFieldSizeTwo.getText() != null )
                System.out.println( "Pad Two size invalid." );
        }
        try
        {
            speedOne = Integer.parseInt( jTextFieldSpeedOne.getText() );
            if( speedOne > 10 )
                speedOne = 10;

            canvas.setPad1Speed( speedOne );
        }
        catch( Exception e )
        {
            if( jTextFieldSpeedOne.getText() != null )
                System.out.println( "Pad One speed invalid." );
        }

        try
        {
            speedTwo = Integer.parseInt( jTextFieldSpeedTwo.getText() );
            if( speedTwo > 10 )
                speedTwo = 10;

            canvas.setPad2Speed( speedTwo );
        }
        catch( Exception e )
        {
            if( jTextFieldSpeedTwo.getText() != null )
                System.out.println( "Pad Two speed invalid." );
        }

        this.setVisible( false );
}//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * Closes the frame
     * @param evt - the event
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Calls the frame to change the color of paddle one
     * @param evt - the event
     */
    private void ButtonCol1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonCol1ActionPerformed
    {//GEN-HEADEREND:event_ButtonCol1ActionPerformed
        // TODO add your handling code here:
        PaddleOneColor col = new PaddleOneColor( canvas, this );
        col.setVisible( true );
    }//GEN-LAST:event_ButtonCol1ActionPerformed
    /**
     * Calls the frame to change the color of paddle two
     * @param evt - the event
     */
    private void ButtonCol2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonCol2ActionPerformed
    {//GEN-HEADEREND:event_ButtonCol2ActionPerformed
        // TODO add your handling code here:
        PaddleTwoColor col = new PaddleTwoColor( canvas, this );
        col.setVisible( true );
    }//GEN-LAST:event_ButtonCol2ActionPerformed

    /**
     * Allows for the up button to be set for paddle one
     * @param evt - the event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buttonFocus[0] = true;
        buttonFocus[1] = false;
        buttonFocus[2] = false;
        buttonFocus[3] = false;

    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Allows for the down button to be set for paddle one
     * @param evt - the event
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        buttonFocus[0] = false;
        buttonFocus[1] = true;
        buttonFocus[2] = false;
        buttonFocus[3] = false;
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Allows for the up button to be set for paddle two
     * @param evt - the event
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        buttonFocus[0] = false;
        buttonFocus[1] = false;
        buttonFocus[2] = true;
        buttonFocus[3] = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Allows for the down button to be set for paddle two
     * @param evt - the event
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        // TODO add your handling code here:
        buttonFocus[0] = false;
        buttonFocus[1] = false;
        buttonFocus[2] = false;
        buttonFocus[3] = true;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Changes the color for the paddle option
     * @param color - the color of paddle one
     */
    public void changePad1Color( Color color )
    {
        Pad1Color.setBackground( color );
    }
    /**
     * Changes the color for the paddle option
     * @param color - the color of paddle two
     */
    public void changePad2Color( Color color )
    {
        Pad2Color.setBackground( color );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCol1;
    private javax.swing.JButton ButtonCol2;
    private javax.swing.JLabel P1Down;
    private javax.swing.JLabel P1Up;
    private javax.swing.JLabel P2Down;
    private javax.swing.JLabel P2Up;
    private javax.swing.JPanel Pad1Color;
    private javax.swing.JPanel Pad2Color;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldSizeOne;
    private javax.swing.JTextField jTextFieldSizeTwo;
    private javax.swing.JTextField jTextFieldSpeedOne;
    private javax.swing.JTextField jTextFieldSpeedTwo;
    // End of variables declaration//GEN-END:variables

    /**
     * Needed for the key events
     * @param e - the event
     */
    public void keyTyped( KeyEvent e )
    {
    }
    /**
     * Allows for the setting of the directional buttons
     * @param e - the event
     */
    public void keyPressed( KeyEvent e )
    {
        int x = e.getKeyCode();

        if( buttonFocus[0] )
        {
            canvas.setP1Up( x );
            P1Up.setText( "" + ( char ) x );
            buttonFocus[0] = false;
        }
        else if( buttonFocus[1] )
        {
            canvas.setP1Down( x );
            P1Down.setText( "" + ( char ) x );
            buttonFocus[1] = false;
        }
        else if( buttonFocus[2] )
        {
            canvas.setP2Up( x );
            P2Up.setText( "" + ( char ) x );
            buttonFocus[2] = false;
        }
        else if( buttonFocus[3] )
        {
            canvas.setP2Down( x );
            P2Down.setText( "" + ( char ) x );
            buttonFocus[3] = false;
        }
    }
    /**
     * Needed for the key events
     * @param e - the event
     */
    public void keyReleased( KeyEvent e )
    {
    }
}
