/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayOption.java
 *
 * Created on May 5, 2010, 7:01:22 PM
 */
package pongproject;

import java.awt.Color;

/**
 * Contians the options for the players
 * @author Mark & Sam
 */
public class PlayOption extends javax.swing.JFrame
{

    /** The canvas of the program*/
    PongCanvas canvas;

    /**
     * Creates new form PlayOption
     * @param canvas - the canvas of the program
     */
    public PlayOption( PongCanvas canvas )
    {
        this.canvas = canvas;
        initComponents();
        if( canvas.isComputer() )
        {
            Computer.setText( "Computer" );
        }
        else
        {
            Computer.setText( "Two Player" );
        }

        if( canvas.getSeizureMode() )
        {
            seizureMode.setText( "Enabled" );
        }
        else
        {
            seizureMode.setText( "Disabled" );
        }

        BackgroundColor.setBackground( canvas.getBackgroundColor() );

        if( canvas.getCompDifficulty() == 1 )
        {
            buttonGroup1.setSelected( Easy.getModel(), true );
        }
        else if( canvas.getCompDifficulty() == 2 )
        {
            buttonGroup1.setSelected( Moderate.getModel(), true );
        }
        else if( canvas.getCompDifficulty() > 4 || canvas.getCompDifficulty() < 1 )
        {
            buttonGroup1.setSelected( Normal.getModel(), true );
        }
        else if( canvas.getCompDifficulty() == 3 )
        {
            buttonGroup1.setSelected( Hard.getModel(), true );
        }
        else if( canvas.getCompDifficulty() == 4 )
        {
            buttonGroup1.setSelected( Hardcore.getModel(), true );
        }
        this.setLocation( canvas.getX(), canvas.getY() );

    }

    public void changeBackgroundColor( Color color )
    {
        BackgroundColor.setBackground( color );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Computer = new javax.swing.JButton();
        Easy = new javax.swing.JRadioButton();
        Moderate = new javax.swing.JRadioButton();
        Normal = new javax.swing.JRadioButton();
        Hard = new javax.swing.JRadioButton();
        Hardcore = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        seizureMode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BackgroundColor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pongproject.PongProjectApp.class).getContext().getResourceMap(PlayOption.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        Computer.setText(resourceMap.getString("Computer.text")); // NOI18N
        Computer.setName("Computer"); // NOI18N
        Computer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerActionPerformed(evt);
            }
        });

        buttonGroup1.add(Easy);
        Easy.setText(resourceMap.getString("Easy.text")); // NOI18N
        Easy.setName("Easy"); // NOI18N

        buttonGroup1.add(Moderate);
        Moderate.setText(resourceMap.getString("Moderate.text")); // NOI18N
        Moderate.setName("Moderate"); // NOI18N

        buttonGroup1.add(Normal);
        Normal.setText(resourceMap.getString("Normal.text")); // NOI18N
        Normal.setName("Normal"); // NOI18N

        buttonGroup1.add(Hard);
        Hard.setText(resourceMap.getString("Hard.text")); // NOI18N
        Hard.setName("Hard"); // NOI18N

        buttonGroup1.add(Hardcore);
        Hardcore.setText(resourceMap.getString("Hardcore.text")); // NOI18N
        Hardcore.setName("Hardcore"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        OK.setText(resourceMap.getString("OK.text")); // NOI18N
        OK.setName("OK"); // NOI18N
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Cancel.setText(resourceMap.getString("Cancel.text")); // NOI18N
        Cancel.setName("Cancel"); // NOI18N
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        seizureMode.setText(resourceMap.getString("seizureMode.text")); // NOI18N
        seizureMode.setName("seizureMode"); // NOI18N
        seizureMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seizureModeActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BackgroundColor.setName("BackgroundColor"); // NOI18N

        javax.swing.GroupLayout BackgroundColorLayout = new javax.swing.GroupLayout(BackgroundColor);
        BackgroundColor.setLayout(BackgroundColorLayout);
        BackgroundColorLayout.setHorizontalGroup(
            BackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        BackgroundColorLayout.setVerticalGroup(
            BackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Moderate)
                                    .addComponent(Easy)
                                    .addComponent(Normal)
                                    .addComponent(Hard)
                                    .addComponent(Hardcore))
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(BackgroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Computer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seizureMode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seizureMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Computer, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Easy)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Moderate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Normal))
                            .addComponent(BackgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hardcore)
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets if the computer is playing
     * @param evt - the event
     */
    private void ComputerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ComputerActionPerformed
    {//GEN-HEADEREND:event_ComputerActionPerformed
        // TODO add your handling code here:
        if( canvas.isComputer() )
        {
            canvas.setTwoPlayer( false );
            Computer.setText( "Two Player" );
        }
        else
        {
            canvas.setTwoPlayer( true );
            Computer.setText( "Computer " );
        }
    }//GEN-LAST:event_ComputerActionPerformed

    /**
     * Finalizes the options
     * @param evt - the event
     */
    private void OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OKActionPerformed
    {//GEN-HEADEREND:event_OKActionPerformed
        // TODO add your handling code here:
        if( buttonGroup1.isSelected( Easy.getModel() ) )
        {
            canvas.setComputerDifficulty( 1 );
        }
        else if( buttonGroup1.isSelected( Moderate.getModel() ) )
        {
            canvas.setComputerDifficulty( 2 );
        }
        else if( buttonGroup1.isSelected( Normal.getModel() ) )
        {
            canvas.setComputerDifficulty( 5 );
        }
        else if( buttonGroup1.isSelected( Hard.getModel() ) )
        {
            canvas.setComputerDifficulty( 3 );
        }
        else if( buttonGroup1.isSelected( Hardcore.getModel() ) )
        {
            canvas.setComputerDifficulty( 4 );
        }


        this.setVisible( false );
    }//GEN-LAST:event_OKActionPerformed

    /**
     * Closes the frame
     * @param evt - the event
     */
    private void CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelActionPerformed
    {//GEN-HEADEREND:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible( false );
    }//GEN-LAST:event_CancelActionPerformed

    private void seizureModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_seizureModeActionPerformed
    {//GEN-HEADEREND:event_seizureModeActionPerformed
        // TODO add your handling code here:
        if( canvas.getSeizureMode() )
        {
            canvas.setSeizureMode( false );
            seizureMode.setText( "Disabled" );
        }
        else
        {
            canvas.setSeizureMode( true );
            seizureMode.setText( "Enabled" );
        }
    }//GEN-LAST:event_seizureModeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BackgroundColor col = new BackgroundColor( canvas, this);
        col.setVisible( true);

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundColor;
    private javax.swing.JPanel BallColor;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Computer;
    private javax.swing.JRadioButton Easy;
    private javax.swing.JRadioButton Hard;
    private javax.swing.JRadioButton Hardcore;
    private javax.swing.JRadioButton Moderate;
    private javax.swing.JRadioButton Normal;
    private javax.swing.JButton OK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton seizureMode;
    // End of variables declaration//GEN-END:variables
}
